--Creacion de rol de vendedor de tienda
USE [Northwind]
GO
CREATE ROLE [ROL_VENDEDOR_TIENDA]
GO

--Creación de permisos para el rol de vendedor de tienda
use [Northwind]
GO
GRANT DELETE ON [dbo].[Orders] TO [ROL_VENDEDOR_TIENDA]
GO
use [Northwind]
GO
GRANT INSERT ON [dbo].[Orders] TO [ROL_VENDEDOR_TIENDA]
GO
use [Northwind]
GO
GRANT SELECT ON [dbo].[Orders] TO [ROL_VENDEDOR_TIENDA]
GO
use [Northwind]
GO
GRANT UPDATE ON [dbo].[Orders] TO [ROL_VENDEDOR_TIENDA]
GO
use [Northwind]
GO
GRANT DELETE ON [dbo].[Order Details] TO [ROL_VENDEDOR_TIENDA]
GO
use [Northwind]
GO
GRANT INSERT ON [dbo].[Order Details] TO [ROL_VENDEDOR_TIENDA]
GO
use [Northwind]
GO
GRANT SELECT ON [dbo].[Order Details] TO [ROL_VENDEDOR_TIENDA]
GO
use [Northwind]
GO
GRANT UPDATE ON [dbo].[Order Details] TO [ROL_VENDEDOR_TIENDA]
GO


--CREACION DE LOGIN PARA URSULA PEREZ
USE [master]
GO
CREATE LOGIN [uperez] WITH PASSWORD=N'uperez', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [Northwind]
GO
CREATE USER [uperez] FOR LOGIN [uperez]
GO
--CREACION DE USUARIO PARA URSULA PEREZ
USE [Northwind]
GO
ALTER USER [uperez] WITH DEFAULT_SCHEMA=[dbo]
GO
USE [Northwind]
GO
ALTER ROLE [ROL_VENDEDOR_TIENDA] ADD MEMBER [uperez]
GO

--CREACION DE LOGIN PARA PETER MARTINEZ
USE [master]
GO
CREATE LOGIN [pmartinez]
WITH PASSWORD=N'pmartinez',
DEFAULT_DATABASE=[master], 
CHECK_EXPIRATION=OFF, 
CHECK_POLICY=OFF
GO
--CREACION DE USUARIO PARA PETER MARTINEZ
USE [Northwind]
GO
CREATE USER [pmartinez] FOR LOGIN [pmartinez]
GO
USE [Northwind]
GO
ALTER ROLE [ROL_VENDEDOR_TIENDA] ADD MEMBER [pmartinez]
GO


--CREACION DE LOGIN PARA PETER VANNELS
USE [master]
GO
CREATE LOGIN [pvannels] WITH PASSWORD=N'pvannels', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
--CREACION DE USUARIO PARA PETER VANNELS
USE [Northwind]
GO
CREATE USER [pvannels] FOR LOGIN [pvannels]
GO
USE [Northwind]
GO
ALTER ROLE [ROL_VENDEDOR_TIENDA] ADD MEMBER [pvannels]
GO

--CREACION LOGIN GEORGE SMITH
USE [master]
GO
CREATE LOGIN [gsmith] WITH PASSWORD=N'gsmith', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
--CREACION USUARIO GEORGE SMITH
USE [Northwind]
GO
CREATE USER [gsmith] FOR LOGIN [gsmith]
GO
USE [Northwind]
GO
ALTER ROLE [ROL_VENDEDOR_TIENDA] ADD MEMBER [gsmith]
GO