USE [master]
GO
ALTER DATABASE [EduTec] ADD FILEGROUP [aaaaaaaa]
GO
ALTER DATABASE [EduTec] ADD FILEGROUP [FG-GUSTAVO]
GO
ALTER DATABASE [EduTec] ADD FILE ( NAME = N'ARCHIVO2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ARCHIVO2.LDF' , SIZE = 8192KB , FILEGROWTH = 65536KB ) TO FILEGROUP [FG-GUSTAVO]
GO
