USE [Northwind]
GO
CREATE ROLE [ROL_VICEPRESIDENTE]
GO

GRANT DELETE ON [dbo].[Employees] TO [ROL_VICEPRESIDENTE]

GO
GRANT INSERT ON [dbo].[Employees] TO [ROL_VICEPRESIDENTE]
GO

GRANT SELECT ON [dbo].[Employees] TO [ROL_VICEPRESIDENTE]
GO

GRANT UPDATE ON [dbo].[Employees] TO [ROL_VICEPRESIDENTE]
GO

GRANT SELECT ON [dbo].[Orders] TO [ROL_VICEPRESIDENTE]
GO

GRANT SELECT ON [dbo].[Order Details] TO [ROL_VICEPRESIDENTE]
GO
