use [Northwind]
GO
CREATE ROLE [ROL_GERENTE_VENTAS]
GO

GRANT DELETE ON [dbo].[Categories] TO [ROL_GERENTE_VENTAS]

GO
GRANT INSERT ON [dbo].[Categories] TO [ROL_GERENTE_VENTAS]

GO
GRANT SELECT ON [dbo].[Categories] TO [ROL_GERENTE_VENTAS]

GO
GRANT UPDATE ON [dbo].[Categories] TO [ROL_GERENTE_VENTAS]

GO
GRANT DELETE ON [dbo].[Order Details] TO [ROL_GERENTE_VENTAS]

GO
GRANT SELECT ON [dbo].[Order Details] TO [ROL_GERENTE_VENTAS]

GO
GRANT DELETE ON [dbo].[Orders] TO [ROL_GERENTE_VENTAS]

GO
GRANT SELECT ON [dbo].[Orders] TO [ROL_GERENTE_VENTAS]

GO
GRANT DELETE ON [dbo].[Products] TO [ROL_GERENTE_VENTAS]

GO
GRANT INSERT ON [dbo].[Products] TO [ROL_GERENTE_VENTAS]

GO
GRANT SELECT ON [dbo].[Products] TO [ROL_GERENTE_VENTAS]

GO
GRANT UPDATE ON [dbo].[Products] TO [ROL_GERENTE_VENTAS]

