use [Northwind]
GO

CREATE ROLE [ROL_ADMINISTRADOR_INTERNO]
GO


GO
GRANT DELETE ON [dbo].[Products] TO [ROL_ADMINISTRADOR_INTERNO]

GO
GRANT INSERT ON [dbo].[Products] TO [ROL_ADMINISTRADOR_INTERNO]

GO
GRANT SELECT ON [dbo].[Products] TO [ROL_ADMINISTRADOR_INTERNO]

GO
GRANT UPDATE ON [dbo].[Products] TO [ROL_ADMINISTRADOR_INTERNO]

GO
GRANT DELETE ON [dbo].[Categories] TO [ROL_ADMINISTRADOR_INTERNO]

GO
GRANT INSERT ON [dbo].[Categories] TO [ROL_ADMINISTRADOR_INTERNO]

GO
GRANT SELECT ON [dbo].[Categories] TO [ROL_ADMINISTRADOR_INTERNO]

GO
GRANT UPDATE ON [dbo].[Categories] TO [ROL_ADMINISTRADOR_INTERNO]

GO
GRANT DELETE ON [dbo].[Shippers] TO [ROL_ADMINISTRADOR_INTERNO]

GO
GRANT INSERT ON [dbo].[Shippers] TO [ROL_ADMINISTRADOR_INTERNO]

GO
GRANT SELECT ON [dbo].[Shippers] TO [ROL_ADMINISTRADOR_INTERNO]

GO
GRANT UPDATE ON [dbo].[Shippers] TO [ROL_ADMINISTRADOR_INTERNO]



