USE [Northwind]
GO
CREATE ROLE [ROL_VENDEDOR_TIENDA]

GO
GRANT DELETE ON [dbo].[Order Details] TO [ROL_VENDEDOR_TIENDA]

GO
GRANT INSERT ON [dbo].[Order Details] TO [ROL_VENDEDOR_TIENDA]

GO
GRANT SELECT ON [dbo].[Order Details] TO [ROL_VENDEDOR_TIENDA]

GO
GRANT UPDATE ON [dbo].[Order Details] TO [ROL_VENDEDOR_TIENDA]

GO
GRANT DELETE ON [dbo].[Orders] TO [ROL_VENDEDOR_TIENDA]

GO
GRANT INSERT ON [dbo].[Orders] TO [ROL_VENDEDOR_TIENDA]

GO
GRANT SELECT ON [dbo].[Orders] TO [ROL_VENDEDOR_TIENDA]

GO
GRANT UPDATE ON [dbo].[Orders] TO [ROL_VENDEDOR_TIENDA]
