-- CREACION USUARIOS - ASIGNACION ROL_ViCEPRESIDENTE
USE [master]
GO
CREATE LOGIN [afuller] WITH PASSWORD=N'!dsf4g!aasMMS1' MUST_CHANGE, DEFAULT_DATABASE=[master], CHECK_EXPIRATION=off, CHECK_POLICY=ON
GO
USE [Northwind]
GO
CREATE USER [afuller] FOR LOGIN [afuller]
GO
ALTER USER [afuller] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [ROL_ViCEPRESIDENTE] ADD MEMBER [afuller]
GO


-- CREACION USUARIOS - ASIGNACION ROL_VENTAS_CORPORATIVAS
-- Janet Leverling
USE [master]
GO
CREATE LOGIN jleverling WITH PASSWORD=N'!dsf4g!aasMMS2' MUST_CHANGE, DEFAULT_DATABASE=[master], CHECK_EXPIRATION=off, CHECK_POLICY=ON
GO
USE [Northwind]
GO
CREATE USER [jleverling] FOR LOGIN [jleverling]
GO
ALTER USER [jleverling] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [ROL_VENTAS_CORPORATIVAS] ADD MEMBER [jleverling]
GO

-- Margaret Peacock
USE [master]
GO
CREATE LOGIN mpeacock WITH PASSWORD=N'!dsf4g!aasMMS3' MUST_CHANGE, DEFAULT_DATABASE=[master], CHECK_EXPIRATION=off, CHECK_POLICY=ON
GO
USE [Northwind]
GO
CREATE USER [mpeacock] FOR LOGIN [mpeacock]
GO
ALTER USER [mpeacock] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [ROL_VENTAS_CORPORATIVAS] ADD MEMBER [mpeacock]
GO


-- CREACION USUARIOS - ASIGNACION ROL_GERENTE_VENTAS
--Steve Buchanan

USE [master]
GO
CREATE LOGIN sbuchanan WITH PASSWORD=N'!dsf4g!aasMMS4' MUST_CHANGE, DEFAULT_DATABASE=[master], CHECK_EXPIRATION=off, CHECK_POLICY=ON
GO
USE [Northwind]
GO
CREATE USER [sbuchanan] FOR LOGIN [sbuchanan]
GO
ALTER USER [sbuchanan] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [ROL_GERENTE_VENTAS] ADD MEMBER [sbuchanan]
GO


-- CREACION USUARIOS - ASIGNACION ROL_VENTAS_LOCALES
--Michael Suyama (msuyama),
USE [master]
GO
CREATE LOGIN msuyama WITH PASSWORD=N'!dsf4g!aasMMS5' MUST_CHANGE, DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [Northwind]
GO
CREATE USER [msuyama] FOR LOGIN [msuyama]
GO
ALTER USER [msuyama] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [ROL_VENTAS_LOCALES] ADD MEMBER [msuyama]
GO

--Robert King (rking)
USE [master]
GO
CREATE LOGIN rking WITH PASSWORD=N'!dsf4g!aasMMS6' MUST_CHANGE, DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [Northwind]
GO
CREATE USER [rking] FOR LOGIN [rking]
GO
ALTER USER [rking] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [ROL_VENTAS_LOCALES] ADD MEMBER [rking]
GO

--Anne Dodsworth (adodsworth)
USE [master]
GO
CREATE LOGIN adodsworth WITH PASSWORD=N'!dsf4g!aasMMS7' MUST_CHANGE, DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [Northwind]
GO
CREATE USER [adodsworth] FOR LOGIN [adodsworth]
GO
ALTER USER [adodsworth] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [ROL_VENTAS_LOCALES] ADD MEMBER [adodsworth]
GO


-- CREACION USUARIOS - ASIGNACION ROL_ADMINISTRADOR_INTERNO
--Laura Callahan (lcallahan)
USE [master]
GO
CREATE LOGIN lcallahan WITH PASSWORD=N'!dsf4g!aasMMS8' MUST_CHANGE, DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [Northwind]
GO
CREATE USER [lcallahan] FOR LOGIN [lcallahan]
GO
ALTER USER [lcallahan] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [ROL_ADMINISTRADOR_INTERNO] ADD MEMBER [lcallahan]
GO


-- CREACION USUARIOS - ASIGNACION ROL_VENDEDOR_TIENDA
--Ursula Pérez (uperez),
USE [master]
GO
CREATE LOGIN uperez WITH PASSWORD=N'!dsf4g!aasMMS9' MUST_CHANGE, DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [Northwind]
GO
CREATE USER [uperez] FOR LOGIN [uperez]
GO
ALTER USER [uperez] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [ROL_VENDEDOR_TIENDA] ADD MEMBER [uperez]
GO

--George Smith (gsmith),
USE [master]
GO
CREATE LOGIN gsmith WITH PASSWORD=N'!dsf4g!aasMMS10' MUST_CHANGE, DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [Northwind]
GO
CREATE USER [gsmith] FOR LOGIN [gsmith]
GO
ALTER USER [gsmith] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [ROL_VENDEDOR_TIENDA] ADD MEMBER [gsmith]
GO

--Peter Vannels (pvannels),
USE [master]
GO
CREATE LOGIN pvannels WITH PASSWORD=N'!dsf4g!aasMMS11' MUST_CHANGE, DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [Northwind]
GO
CREATE USER [pvannels] FOR LOGIN [pvannels]
GO
ALTER USER [pvannels] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [ROL_VENDEDOR_TIENDA] ADD MEMBER [pvannels]
GO

--Peter Martinez (pmartinez)
USE [master]
GO
CREATE LOGIN pmartinez WITH PASSWORD=N'!dsf4g!aasMMS12' MUST_CHANGE, DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [Northwind]
GO
CREATE USER [pmartinez] FOR LOGIN [pmartinez]
GO
ALTER USER [pmartinez] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [ROL_VENDEDOR_TIENDA] ADD MEMBER [pmartinez]
GO